spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_basket
    username: dev
    password: dev1234
  messages:
    basename: messages, errors

server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always

